import { PaletteScale, PaletteStyle } from './types'

export enum Colors {
  PRIMARY_FIRST = '#8352FD',
  PRIMARY_SECOND = '#2B1133',
  PRIMARY_THIRD = '#371641',
  PRIMARY_FOURTH = '#612773',
  PRIMARY_FIFTH = '#CCA0D9',
  SECONDARY_FIRST = '#B28138',
  SECONDARY_SECOND = '#E5A648',
  SECONDARY_THIRD = '#FFB850',
  SECONDARY_FOURTH = '#FFCC82',
  SECONDARY_FIFTH = '#FFEBCF',
  TEXT = '#252529',
  TRANSPARENT = 'transparent',
  SECONDARY_ACCENT_SUCCESS_GREEN90 = '#0E441C',
  SECONDARY_ACCENT_SUCCESS_GREEN70 = '#166D2E',
  SECONDARY_ACCENT_SUCCESS_GREEN50 = '#20A144',
  SECONDARY_ACCENT_SUCCESS_GREEN30 = '#76B888',
  SECONDARY_ACCENT_SUCCESS_GREEN10 = '#DFEDE8',
  SECONDARY_ACCENT_INFO_BLUE90 = '#182256',
  SECONDARY_ACCENT_INFO_BLUE70 = '#263689',
  SECONDARY_ACCENT_INFO_BLUE50 = '#3044AB',
  SECONDARY_ACCENT_INFO_BLUE30 = '#838FCD',
  SECONDARY_ACCENT_INFO_BLUE10 = '#D6DAEE',
  SECONDARY_ACCENT_ERROR_RED90 = '#691212',
  SECONDARY_ACCENT_ERROR_RED70 = '#A81E1E',
  SECONDARY_ACCENT_ERROR_RED50 = '#D22525',
  SECONDARY_ACCENT_ERROR_RED30 = '#E47C7C',
  SECONDARY_ACCENT_ERROR_RED10 = '#F6D3D3',
  THIRD_SURFACE_GREYSCALE90 = '#1E1B20',
  THIRD_SURFACE_GREYSCALE70 = '#474747',
  THIRD_SURFACE_GREYSCALE50 = '#BFBFBF',
  THIRD_SURFACE_GREYSCALE30 = '#F8F7F4',
  THIRD_SURFACE_GREYSCALE10 = '#FAFAFA',
  WHITE = '#FFFFFF',
  BLACK = '#000000',
}

export const Palette: PaletteStyle<string> = {
  TEXT: Colors.TEXT,
  PRIMARY_FIRST: Colors.PRIMARY_FIRST,
  PRIMARY_SECOND: Colors.PRIMARY_SECOND,
  PRIMARY_THIRD: Colors.PRIMARY_THIRD,
  PRIMARY_FOURTH: Colors.PRIMARY_FOURTH,
  PRIMARY_FIFTH: Colors.PRIMARY_FIFTH,
  SECONDARY_FIRST: Colors.SECONDARY_FIRST,
  SECONDARY_SECOND: Colors.SECONDARY_SECOND,
  SECONDARY_THIRD: Colors.SECONDARY_THIRD,
  SECONDARY_FOURTH: Colors.SECONDARY_FOURTH,
  SECONDARY_FIFTH: Colors.SECONDARY_FIFTH,
  TRANSPARENT: Colors.TRANSPARENT,
  SECONDARY_ACCENT_SUCCESS_GREEN90: Colors.SECONDARY_ACCENT_SUCCESS_GREEN90,
  SECONDARY_ACCENT_SUCCESS_GREEN70: Colors.SECONDARY_ACCENT_SUCCESS_GREEN70,
  SECONDARY_ACCENT_SUCCESS_GREEN50: Colors.SECONDARY_ACCENT_SUCCESS_GREEN50,
  SECONDARY_ACCENT_SUCCESS_GREEN30: Colors.SECONDARY_ACCENT_SUCCESS_GREEN30,
  SECONDARY_ACCENT_SUCCESS_GREEN10: Colors.SECONDARY_ACCENT_SUCCESS_GREEN10,
  SECONDARY_ACCENT_INFO_BLUE90: Colors.SECONDARY_ACCENT_INFO_BLUE90,
  SECONDARY_ACCENT_INFO_BLUE70: Colors.SECONDARY_ACCENT_INFO_BLUE70,
  SECONDARY_ACCENT_INFO_BLUE50: Colors.SECONDARY_ACCENT_INFO_BLUE50,
  SECONDARY_ACCENT_INFO_BLUE30: Colors.SECONDARY_ACCENT_INFO_BLUE30,
  SECONDARY_ACCENT_INFO_BLUE10: Colors.SECONDARY_ACCENT_INFO_BLUE10,
  SECONDARY_ACCENT_ERROR_RED90: Colors.SECONDARY_ACCENT_ERROR_RED90,
  SECONDARY_ACCENT_ERROR_RED70: Colors.SECONDARY_ACCENT_ERROR_RED70,
  SECONDARY_ACCENT_ERROR_RED50: Colors.SECONDARY_ACCENT_ERROR_RED50,
  SECONDARY_ACCENT_ERROR_RED30: Colors.SECONDARY_ACCENT_ERROR_RED30,
  SECONDARY_ACCENT_ERROR_RED10: Colors.SECONDARY_ACCENT_ERROR_RED10,
  THIRD_SURFACE_GREYSCALE90: Colors.THIRD_SURFACE_GREYSCALE90,
  THIRD_SURFACE_GREYSCALE70: Colors.THIRD_SURFACE_GREYSCALE70,
  THIRD_SURFACE_GREYSCALE50: Colors.THIRD_SURFACE_GREYSCALE50,
  THIRD_SURFACE_GREYSCALE30: Colors.THIRD_SURFACE_GREYSCALE30,
  THIRD_SURFACE_GREYSCALE10: Colors.THIRD_SURFACE_GREYSCALE10,
  WHITE: Colors.WHITE,
  BLACK: Colors.BLACK,
}

function checkOpacityValue(opacity: number) {
  if (opacity < 0 || opacity > 1) {
    throw new Error(`opacity must between 0 and 1, got ${opacity}`)
  }
}

export const colorTranslucent = (color: PaletteScale, opacity: number) => {
  const colorToOpaque = Palette[color]
  var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(colorToOpaque)
  if (!result) {
    throw new Error(`Error in opacity`)
  }
  return `rgba(${parseInt(result[1], 16)}, ${parseInt(
    result[2],
    16,
  )}, ${parseInt(result[3], 16)},  ${opacity})`
}

export function blackTranslucent(opacity: number) {
  checkOpacityValue(opacity)
  return `rgba(0, 0, 0, ${opacity})`
}
