import { TextStyle } from 'react-native'

export interface ITheme {
  colors: PaletteStyle<string>
  typography: TypographyStyle<TextStyle>
  spacing: SpacingStyle<number>
}

export enum TypographyScale {
  HEADING_BOLD1 = 'HEADING_BOLD1',
  HEADING_BOLD2 = 'HEADING_BOLD2',
  HEADING_SEMI_BOLD3 = 'HEADING_SEMI_BOLD3',
  PARAGRAPH_REGULAR1 = 'PARAGRAPH_REGULAR1',
  PARAGRAPH_REGULAR2 = 'PARAGRAPH_REGULAR2',
  PARAGRAPH_BOLD2 = 'PARAGRAPH_BOLD2',
  BODY_BOLD = 'BODY_BOLD',
  BODY_REGULAR = 'BODY_REGULAR',
  LINK_REGULAR = 'LINK_REGULAR',
  ACTION_REGULAR = 'ACTION_REGULAR',
}

export interface TypographyStyle<T> {
  [TypographyScale.HEADING_BOLD1]: T
  [TypographyScale.HEADING_BOLD2]: T
  [TypographyScale.HEADING_SEMI_BOLD3]: T
  [TypographyScale.PARAGRAPH_REGULAR1]: T
  [TypographyScale.PARAGRAPH_REGULAR2]: T
  [TypographyScale.PARAGRAPH_BOLD2]: T
  [TypographyScale.BODY_BOLD]: T
  [TypographyScale.BODY_REGULAR]: T
  [TypographyScale.LINK_REGULAR]: T
  [TypographyScale.ACTION_REGULAR]: T
}

export enum PaletteScale {
  'PRIMARY_FIRST' = 'PRIMARY_FIRST',
  'PRIMARY_SECOND' = 'PRIMARY_SECOND',
  'PRIMARY_THIRD' = 'PRIMARY_THIRD',
  'PRIMARY_FOURTH' = 'PRIMARY_FOURTH',
  'PRIMARY_FIFTH' = 'PRIMARY_FIFTH',
  'SECONDARY_FIRST' = 'SECONDARY_FIRST',
  'SECONDARY_SECOND' = 'SECONDARY_SECOND',
  'SECONDARY_THIRD' = 'SECONDARY_THIRD',
  'SECONDARY_FOURTH' = 'SECONDARY_FOURTH',
  'SECONDARY_FIFTH' = 'SECONDARY_FIFTH',
  'TEXT' = 'TEXT',
  'TRANSPARENT' = 'TRANSPARENT',
  'SECONDARY_ACCENT_SUCCESS_GREEN90' = 'SECONDARY_ACCENT_SUCCESS_GREEN90',
  'SECONDARY_ACCENT_SUCCESS_GREEN70' = 'SECONDARY_ACCENT_SUCCESS_GREEN70',
  'SECONDARY_ACCENT_SUCCESS_GREEN50' = 'SECONDARY_ACCENT_SUCCESS_GREEN50',
  'SECONDARY_ACCENT_SUCCESS_GREEN30' = 'SECONDARY_ACCENT_SUCCESS_GREEN30',
  'SECONDARY_ACCENT_SUCCESS_GREEN10' = 'SECONDARY_ACCENT_SUCCESS_GREEN10',
  'SECONDARY_ACCENT_INFO_BLUE90' = 'SECONDARY_ACCENT_INFO_BLUE90',
  'SECONDARY_ACCENT_INFO_BLUE70' = 'SECONDARY_ACCENT_INFO_BLUE70',
  'SECONDARY_ACCENT_INFO_BLUE50' = 'SECONDARY_ACCENT_INFO_BLUE50',
  'SECONDARY_ACCENT_INFO_BLUE30' = 'SECONDARY_ACCENT_INFO_BLUE30',
  'SECONDARY_ACCENT_INFO_BLUE10' = 'SECONDARY_ACCENT_INFO_BLUE10',
  'SECONDARY_ACCENT_ERROR_RED90' = 'SECONDARY_ACCENT_ERROR_RED90',
  'SECONDARY_ACCENT_ERROR_RED70' = 'SECONDARY_ACCENT_ERROR_RED70',
  'SECONDARY_ACCENT_ERROR_RED50' = 'SECONDARY_ACCENT_ERROR_RED50',
  'SECONDARY_ACCENT_ERROR_RED30' = 'SECONDARY_ACCENT_ERROR_RED30',
  'SECONDARY_ACCENT_ERROR_RED10' = 'SECONDARY_ACCENT_ERROR_RED10',
  'THIRD_SURFACE_GREYSCALE90' = 'THIRD_SURFACE_GREYSCALE90',
  'THIRD_SURFACE_GREYSCALE70' = 'THIRD_SURFACE_GREYSCALE70',
  'THIRD_SURFACE_GREYSCALE50' = 'THIRD_SURFACE_GREYSCALE50',
  'THIRD_SURFACE_GREYSCALE30' = 'THIRD_SURFACE_GREYSCALE30',
  'THIRD_SURFACE_GREYSCALE10' = 'THIRD_SURFACE_GREYSCALE10',
  'WHITE' = 'WHITE',
  'BLACK' = 'BLACK',
}

export interface PaletteStyle<T> {
  [PaletteScale.PRIMARY_FIRST]: T
  [PaletteScale.PRIMARY_SECOND]: T
  [PaletteScale.PRIMARY_THIRD]: T
  [PaletteScale.PRIMARY_FOURTH]: T
  [PaletteScale.PRIMARY_FIFTH]: T
  [PaletteScale.SECONDARY_FIRST]: T
  [PaletteScale.SECONDARY_SECOND]: T
  [PaletteScale.SECONDARY_THIRD]: T
  [PaletteScale.SECONDARY_FOURTH]: T
  [PaletteScale.SECONDARY_FIFTH]: T
  [PaletteScale.TEXT]: T
  [PaletteScale.TRANSPARENT]: T
  [PaletteScale.SECONDARY_ACCENT_SUCCESS_GREEN90]: T
  [PaletteScale.SECONDARY_ACCENT_SUCCESS_GREEN70]: T
  [PaletteScale.SECONDARY_ACCENT_SUCCESS_GREEN50]: T
  [PaletteScale.SECONDARY_ACCENT_SUCCESS_GREEN30]: T
  [PaletteScale.SECONDARY_ACCENT_SUCCESS_GREEN10]: T
  [PaletteScale.SECONDARY_ACCENT_INFO_BLUE90]: T
  [PaletteScale.SECONDARY_ACCENT_INFO_BLUE70]: T
  [PaletteScale.SECONDARY_ACCENT_INFO_BLUE50]: T
  [PaletteScale.SECONDARY_ACCENT_INFO_BLUE30]: T
  [PaletteScale.SECONDARY_ACCENT_INFO_BLUE10]: T
  [PaletteScale.SECONDARY_ACCENT_ERROR_RED90]: T
  [PaletteScale.SECONDARY_ACCENT_ERROR_RED70]: T
  [PaletteScale.SECONDARY_ACCENT_ERROR_RED50]: T
  [PaletteScale.SECONDARY_ACCENT_ERROR_RED30]: T
  [PaletteScale.SECONDARY_ACCENT_ERROR_RED10]: T
  [PaletteScale.THIRD_SURFACE_GREYSCALE90]: T
  [PaletteScale.THIRD_SURFACE_GREYSCALE70]: T
  [PaletteScale.THIRD_SURFACE_GREYSCALE50]: T
  [PaletteScale.THIRD_SURFACE_GREYSCALE30]: T
  [PaletteScale.THIRD_SURFACE_GREYSCALE10]: T
  [PaletteScale.WHITE]: T
  [PaletteScale.BLACK]: T
}

export enum SpacingScale {
  HORIZONTAL_SCREEN_PADDING = 'HORIZONTAL_SCREEN_PADDING',
}

export interface SpacingStyle<T> {
  [SpacingScale.HORIZONTAL_SCREEN_PADDING]: T
}
